### ISSUE TITLE
dateOf or toTimestamp function in select query

### ISSUE THREAD

**Issue by vizakenjack** [loopsocial/cassandrax#23]
Is there a way to use functions in select query?
I have tsid field with timeuuid type, and it's handy because I use it as a part of primary key and also inserted_at timestamp. To get a timestamp, I use this query:
```
SELECT channel_id, body, dateOf(tsid) FROM keyspace.messages_by_channel;
```

I have tried this: 
```
MessageByChannel |> select(["toDate(tsid)"]) |> Keyspace.all
```

But got:
```
(Xandra.Error) Undefined name toDate(tsid) in selection clause
```

**Comment by tdtadeu** [comment]
Good catch, @vizakenjack! I think it would be more natural if we allowed `fragment`s like `Ecto.Query` does.
Then you'd use fragments inside the select like you do in your query above:

```elixir
MessageByChannel |> select(fragment("toDate(tsid)")) |> Keyspace.all()
MessageByChannel |> select([fragment("toDate(tsid)"), :body]) |> Keyspace.all()
```

I can assist if you're interested in helping support this, I won't be able to actively work on this for a few weeks due to work.
